package enums;

public enum Eventos {
    NADA,
    CANTO_TRUCO,
    CANTO_RETRUCO,
    CANTO_VALE_CUATRO,
    CANTO_ENVIDO,
    CANTO_ENVIDO_DOBLE,
    CANTO_REAL_ENVIDO,
    CANTO_FALTA_ENVIDO,
    MENSAJE,
    CARTA_TIRADAJ1,
    CARTA_TIRADAJ2,
    FIN_MANO,
    FIN_PARTIDA,
    INICIO_PARTIDA,
    LISTA_JUGADORES_DISPONIBLES, // los que no están elegidos
    LISTA_JUGADORES_TOTALES, // para el historial
    PUNTAJES,
    NUEVA_RONDA,
    ABANDONO_PARTIDA,

}
